### ISSUE TITLE
文件乱码

### ISSUE THREAD

**Issue by Familyye** [poorld/badget#1]
com/poorld/badget/fragment
AppSettingsFragment.java

**Comment by poorld** [comment]
> com/poorld/badget/fragment AppSettingsFragment.java

**Comment by poorld** [comment]
等我重新提交

**Comment by poorld** [comment]
更新了，试一下

**Comment by poorld** [comment]
哪几个我这边看不到

**Comment by poorld** [comment]
> 没用还有有几个乱码的文件

现在可以用了吗？

**Comment by poorld** [comment]
> 没用还有有几个乱码的文件

现在可以用了吗？

**Comment by poorld** [comment]
> 

我看看报的啥错
